= Blueprint for Mobile Projects
:link-repository: https://github.com/wmontwe/mobile-project-blueprint
:project_version: 0.1.0
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

++++
<div align="center">
    <p> <!-- PROJECT LOGO -->
        <a href="https://github.com/wmontwe/mobile-project-blueprint">
            <img src="assets/images/logo.svg" width="100"/>
        </a>
    </p>
    <p><!-- PROJECT TITLE -->
        <h3>WIP Blueprint For Mobile Projects</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        A blueprint to kickstart mobile projects.
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="README.adoc"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/wmontwe/mobile-project-blueprint/issues">Report Bug</a>
        ·
        <a href="https://github.com/wmontwe/mobile-project-blueprint/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them-->
        <a href="https://github.com/wmontwe/mobile-project-blueprint/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest release"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents

toc::[]

== About The Project

This is a blueprint for Mobile projects to start right away reducing initial setup cost.

It's supporting:

 * https://developer.android.com/jetpack/[JetPack] with https://developer.android.com/jetpack/androidx/[AndroidX]
 
=== Warning

This project is work in progress. It contains several experiements and will change heavily over time.

It is currently undergoing architectural and organisational changes that focus on renewal of the current approach and removal of experiments.

=== Features

* Kotlin-only
* Android App
* Jetpack Compose
* Material 3
* CI Setup with GitHub Actions
* Publish to GitHub Packages with Github Actions
* Dependency versions managed via gradlePlugin
* Kotlin Static Analysis via ktlint and detekt
* Issues (bug report + feature request) and Pull Request Template

=== Build With

* link

== Getting Started

=== Prerequisites

* Android 5.0.1 (API 21) to Android 11 (API 31)
* Kotlin 1.5.31
* Java 11
* Gradle 7.2
* Android Studio Arctic Fox 2020.3.1 Patch 3, but better Bumblebee for Apple Silicon
* Jetpack Compose 1.0.5

=== Installation

A step by step series of examples that tell you how to get it running.

[source, lanugage]
----
Give the example
----

And repeat

[source, lanugage]
----
until finished
----

End with an example of getting some data out of the system or using a little demo

== Usage

TODO

== Roadmap

This project is work in progress. We are working on adding more functionality, guidelines, documentation and other improvements.

Next planed features:

* feature description

See the open link:{link-repository}/issues[issues] for a list of proposed features and known issues.

== Changelog

See link:CHANGELOG.adoc[changelog]

== Versioning

We use http://semver.org/[Semantic Versioning] as a guideline for our versioning.

Releases use this format: `{major}.{minor}.{patch}`

* Breaking changes bump `{major}` and reset `{minor}` & `{patch}`
* Backward compatible changes bump `{minor}` and reset `{patch}`
* Bug fixes bump `{patch}`

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:docs/Contributing.adoc[Contributing] for details about how to report bugs and propose features.
* link:docs/Developing.adoc[Developing] for details about our development process and how to build and test the project.

== Releasing

See link:docs/Releasing.adoc[releasing]

== Copyright And License

Copyright (c) 2019-2021 Wolf-Martell Montwé. All rights reserved.

== Acknowledgements

* https://github.com/othneildrew/Best-README-Template[Best README Template]
* https://www.talater.com/open-source-templates/#/[Issue and Pull Request Template]
* https://github.com/badoo/Reaktive[Reaktive - Project configuration with Gradle Plugins]
* https://github.com/android/compose-samples/tree/main/Jetsnack[Jetpack Compose Theme by Jetsnack]
