= Badges

== How To Create Badges

We use link:https://shields.io/[Shields.io] to generate Badges.
Please use the link:#_badge_links[badge links section] to document and update currently used badges.
Open the links and download the svg files and place them in the projects `assets/images` folder or use `curl` instead.

== Download Badges

Simply use `curl` to download badges by providing the `url` and `filename`, that starts with `badge`.

[source,bash]
----
curl link -s -o badge-filename
----

== Badge Links

:link-badge-release: https://img.shields.io/badge/Release-0.1.0-blueviolet.svg?style=flat-square
Version image:{link-badge-release}[Latest release]::
`curl {link-badge-release} -s -o badge-release-latest.svg`

:link-badge-platform: https://img.shields.io/badge/Platform-Android%20•%20iOS%20•%20JVM%20•%20JS-blue.svg?style=flat-square
Platform image:{link-badge-platform}[Platform]::
`curl {link-badge-platform} -s -o badge-platform-support.svg`

:link-badge-license: https://img.shields.io/badge/License-PRIVATE-lightgrey.svg?style=flat-square
License image:{link-badge-license}[License]::
`curl {link-badge-license} -s -o badge-license.svg`

== License

Shields is licensed under *Creative Commons Zero v1.0 Universal* (2021-10-16)
