package eu.upwolf.mobile.blueprint.common.ui.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF0062a1)
internal val md_theme_light_onPrimary = Color(0xFFffffff)
internal val md_theme_light_primaryContainer = Color(0xFFcfe4ff)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001d36)
internal val md_theme_light_inversePrimary = Color(0xFFFF9D5E)
internal val md_theme_light_secondary = Color(0xFF526070)
internal val md_theme_light_onSecondary = Color(0xFFffffff)
internal val md_theme_light_secondaryContainer = Color(0xFFd6e4f7)
internal val md_theme_light_onSecondaryContainer = Color(0xFF0f1d2a)
internal val md_theme_light_tertiary = Color(0xFF695779)
internal val md_theme_light_onTertiary = Color(0xFFffffff)
internal val md_theme_light_tertiaryContainer = Color(0xFFf1daff)
internal val md_theme_light_onTertiaryContainer = Color(0xFF241532)
internal val md_theme_light_error = Color(0xFFba1b1b)
internal val md_theme_light_errorContainer = Color(0xFFffdad4)
internal val md_theme_light_onError = Color(0xFFffffff)
internal val md_theme_light_onErrorContainer = Color(0xFF410001)
internal val md_theme_light_background = Color(0xFFfdfcff)
internal val md_theme_light_onBackground = Color(0xFF1a1c1e)
internal val md_theme_light_surface = Color(0xFFfdfcff)
internal val md_theme_light_onSurface = Color(0xFF1a1c1e)
internal val md_theme_light_surfaceVariant = Color(0xFFdfe3eb)
internal val md_theme_light_onSurfaceVariant = Color(0xFF42474e)
internal val md_theme_light_outline = Color(0xFF73777f)
internal val md_theme_light_inverseOnSurface = Color(0xFFf0f0f3)
internal val md_theme_light_inverseSurface = Color(0xFF2f3033)

internal val md_theme_dark_primary = Color(0xFF99cbff)
internal val md_theme_dark_onPrimary = Color(0xFF003256)
internal val md_theme_dark_primaryContainer = Color(0xFF00497a)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFcfe4ff)
internal val md_theme_dark_inversePrimary = Color(0xFF663400)
internal val md_theme_dark_secondary = Color(0xFFbac8db)
internal val md_theme_dark_onSecondary = Color(0xFF243140)
internal val md_theme_dark_secondaryContainer = Color(0xFF3b4857)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFd6e4f7)
internal val md_theme_dark_tertiary = Color(0xFFd5bee6)
internal val md_theme_dark_onTertiary = Color(0xFF3a2a49)
internal val md_theme_dark_tertiaryContainer = Color(0xFF514060)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFf1daff)
internal val md_theme_dark_error = Color(0xFFffb4a9)
internal val md_theme_dark_errorContainer = Color(0xFF930006)
internal val md_theme_dark_onError = Color(0xFF680003)
internal val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
internal val md_theme_dark_background = Color(0xFF1a1c1e)
internal val md_theme_dark_onBackground = Color(0xFFe2e2e6)
internal val md_theme_dark_surface = Color(0xFF1a1c1e)
internal val md_theme_dark_onSurface = Color(0xFFe2e2e6)
internal val md_theme_dark_surfaceVariant = Color(0xFF42474e)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFc3c7cf)
internal val md_theme_dark_outline = Color(0xFF8c9199)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1e)
internal val md_theme_dark_inverseSurface = Color(0xFFe2e2e6)

internal val appThemeSeed = Color(0xFF00629f)
internal val appThemeError = Color(0xFFba1b1b)

internal val appThemeDebugColor = Color.Magenta
